services:
  # SvelteKit application
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env
    restart: unless-stopped
    networks:
      - app-network

  # Hono with Bun application
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000" 
    env_file:
      - ./back/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
