# fly.toml app configuration file generated for nora-toth-fekete on 2025-05-30T09:57:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nora-toth-fekete'
primary_region = 'cdg'

[build]

[[mounts]]
source = 'nora_toth_fekete'
destination = '/apps/front/build/client/static'

[http_service]
internal_port = 5173
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 25
soft_limit = 20

[[services]]
protocol = 'tcp'
internal_port = 3000

[[services.ports]]
port = 3000
handlers = ['tls', 'http']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/apps/front/build/client/static'
url_prefix = '/'
