CREATE TABLE emails (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(100),
    events BOOLEAN,
    updates BOOLEAN,
    locale VARCHAR(5) NOT NULL
);